config/routes.rb
Rails.application.routes.draw do
  
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'welcome#index'

  devise_for :users
  
  # get 'users' => 'users#index' 

  resources :users
  resources :tracks
  resources :comments

  

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # alias_action :update, :destroy, to: :modify
    # can :modify, Comment
  
      user ||= User.new # guest user (not logged in)
      if user.admin?
        can :manage, :all
        # can :assign_roles, User 
        # can [:new, :create, :edit, :update, :destroy], [Producer, Comment]
      else
        can :read, :all
        can [:new, :create], Comment
      end
    
      

    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :track
end

app/models/track.rb
class Track < ActiveRecord::Base
  mount_uploader :song, SongUploader
  belongs_to :user
  has_many :comments
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :comments, through: :tracks
  has_many :tracks

  mount_uploader :image, ImageUploader
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def admin?
    role == 'admin'
  end  

  # def user?
  #   role == 'default'
    



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  # rescue_from CanCan::AccessDenied do |exception|
  #   redirect_to root_url, :alert => exception.message
  # end

  before_filter :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(resource)
  end

  def after_sign_out_path_for(resource)
    welcome_path(resource)
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :first_name << :role << :image
  end

#  before_action :configure_permitted_parameters, if: :devise_controller?
# protected

# def configure_permitted_parameters
#   devise_parameter_sanitizer.for(:sign_up) << :username
# end
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  before_action :authenticate_user!
    # http_basic_authenticate_with name: "abc", password: "secret", only: :destroy
  # can? :update, Comment
  def new
    @comment = Comment.new
  end

  def create
    @user = User.find(params[:user_id])
    @comment = @user.comments.create(comment_params)
    redirect_to user_path(@user)
  end

  def destroy
    @user = User.find(params[:user_id])
    @comment = @user.comments.find(params[:id])
    @comment.destroy
    redirect_to user_path(@user)
  end

  private
    def comment_params
      params.require(:comment).permit(:commenter, :body)
    end
end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController

  # GET /tracks
  # GET /tracks.json
  def index
    @tracks = Track.all
  end

  # GET /tracks/1
  # GET /tracks/1.json
  def show
    @track = Track.find(params[:id])
    @comment = Comment.new
  end

  # GET /tracks/new
  def new
    @track = Track.new
  end

  # GET /tracks/1/edit
  def edit
    @track = Track.find(params[:id])
  end

  # POST /tracks
  # POST /tracks.json
  def create
    @track = Track.new(track_params)

    respond_to do |format|
      if @track.save
        format.html { redirect_to @track, notice: 'Track was successfully created.' }
        format.json { render :show, status: :created, location: @track }
      else
        format.html { render :new }
        format.json { render json: @track.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tracks/1
  # PATCH/PUT /tracks/1.json
  def update
    @track = Track.new(track_params)

    respond_to do |format|
      if @track.update(track_params)
        format.html { redirect_to @track, notice: 'Track was successfully updated.' }
        format.json { render :show, status: :ok, location: @track }
      else
        format.html { render :edit }
        format.json { render json: @track.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tracks/1
  # DELETE /tracks/1.json
  def destroy
    @track = Track.find(params[:track_id])
    @track = @user.track.find(params[:id])
    @track.destroy
    respond_to do |format|
      format.html { redirect_to tracks_url, notice: 'Track was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def track_params
      params.require(:track).permit(:name, :user_id, :description, :song)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user!
  authorize_resource

  def index
    @users = User.all
  end  

  def update
    # authorize! :assign_roles, @user if params[:user][:assign_roles]
  end

  def edit
    @user = User.find(params[:id])
    # render 'users/registrations/edit'
  end

  def show 
    @user = User.find(params[:id])
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  
  def index
    @user = current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/producers_helper.rb
module ProducersHelper
end

app/helpers/tracks_helper.rb
module TracksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/comments/_comment.html.haml
%p
  %strong Commenter:
  = comment.commenter
%p
  %strong Comment:
  = comment.body
%p
  = link_to 'Destroy Comment', [comment.user, comment], |
    method: :delete,                                    |
    data: { confirm: 'Are you sure?' }                  |

app/views/comments/_form.html.haml
= form_for([@producer, @producer.comments.build]) do |f|
  %p
    = f.label :commenter
    %br
      = f.text_field :commenter
  %p
    = f.label :body
    %br
      = f.text_area :body
  %p
    = f.submit

app/views/comments/new.html.haml
= form_for(@comment) do |f|
  %p
    = f.label :commenter
    %br
      = f.text_field :commenter
  %p
    = f.collection_select :track_id, Track.all, :id, :name
  %p
    = f.label :body
    %br
      = f.text_area :body
  %p
    = f.submit

app/views/layouts/application.html.haml
!!!
%html
  %head
  -# = yield :body || "<body>"
    %title MusicProducer
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %p.notice= notice
    %p.alert= alert
    - if user_signed_in?
      %li= link_to('Logout', destroy_user_session_path, :method => :delete)
      -# %li
        -# = link_to('Edit registration', edit_user_registration_path)
    - else
      %li= link_to('Login', new_user_session_path)
      %li= link_to('Register', new_user_registration_path)
    = yield
    %nav

app/views/tracks/_form.html.haml
= simple_form_for(@track) do |f|
  = f.error_notification
  .form-inputs
    = f.input :name
    = f.input :description
    = f.file_field :song
  .form-actions
    = f.hidden_field :user_id, value: current_user.id
    = f.button :submit

app/views/tracks/edit.html.haml
%h1 Editing Track
= render 'form'
= link_to 'Show', @track
|
= link_to 'Back', tracks_path

app/views/tracks/index.html.haml
- content_for :body do
  %body#track
%p#notice= notice
%h1 Listing Tracks
%table
  %thead
    %tr
      %th Name
      %th User
      %th Description
      %th Song
      %th{:colspan => "3"}
  %tbody
    - @tracks.each do |track|
      %tr
        %td= track.name
        %td= track.user_id
        %td= track.description
        %td= track.song
        %td= link_to 'Show', track
        %td= link_to 'Edit', edit_track_path(track)
        %td= link_to 'Destroy', track, method: :delete, data: { confirm: 'Are you sure?' }
%br
  = link_to 'New Track', new_track_path

app/views/tracks/new.html.haml
%h1 New Track
= render 'form'
= link_to 'Back', tracks_path

app/views/tracks/show.html.haml
%p#notice= notice
%p
  %strong Name:
  = @track.name
%p
  %strong User:
  = @track.user.first_name
%p
  %strong Description:
  = @track.description
%p
  %strong Song:
  = audio_tag(@track.song, controls: true)
- if user_signed_in?
  %h2 Add a comment:
  = form_for([@comment]) do |f|
    %p
      = f.label :commenter
      %br
        = f.text_field :commenter, value: current_user.first_name, disabled: true
    %p
      = f.label :body
      %br
        = f.text_area :body
    %p
      = f.submit
= link_to 'Edit', edit_track_path(@track)
|
= link_to 'Back', tracks_path

app/views/users/index.html 16-39-15-484.erb
<!-- <h1>DO NOT SHOW THIS TO ANYONE</h1>
<% @users.each do |user| %>
  <!-- <%= user.first_name %> -->

  <%= user.email %>
  <%= form_for(user) do |f| %>
  <%= radio_button_tag(:role, "producer") %>
  <%= label_tag(:role_producer, "producer") %>
  <%= radio_button_tag(:role, "admin") %>
  <%= label_tag(:role_admin, "admin") %>
  <%= radio_button_tag(:role, "user") %>
  <%= label_tag(:role_user, "user") %>
<!--   <%= f.submit %>
  <% end %> -->
  <br>


<!-- 
  role create a form user which has role as radio button and put submit
 -->

<% end %>

 -->

app/views/users/show.html.haml
- content_for :body do
  %body#show
%li= link_to('All Tracks', tracks_path) 
%p
  %strong Name:
  = @user.first_name
%p
  = image_tag @user.image
- @user.tracks.each do |track|
  = link_to track.name, track
%p
  %strong Bio:
  = @user.bio

app/views/welcome/index.html.haml
- content_for :body do
  %body#welcome
%h1 UnderGround
%p Underground The Place For Producers To Showcase Their Work
.container
- if user_signed_in?
  %li
    = image_tag(current_user.image)
    = link_to "#{current_user.try(:first_name)} Hubb", user_path(current_user)
    - @user.tracks.each do |track|
      = track.name
      = audio_tag(track.song, controls: true )
-# - else
-#   %li
-#     = link_to('Login', new_user_session_path)

app/views/welcome/new.html.erb
index.html.erb2